# Generated by Django 2.2 on 2019-04-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountryCapital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCapitalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('capitals', models.CharField(max_length=200)),
            ],
        ),
    ]
